project:
  type: book
  output-dir: _book

book:
  title: "R for Vital Statistics"
  author: Tesfaye Belay
  repo-url: https://github.com/tech-acs/r4vs
  repo-branch: main
  repo-actions: [edit, issue]
  page-navigation: true
  search: true
    
  page-footer:
    border: true
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>. This work is licensed under a [CC-BY-NC-ND 4.0 Int License](https://creativecommons.org/licenses/by-nc-nd/4.0/)  
    
  chapters:
    - index.qmd
    - intro.qmd
    - setup.qmd
    - implementation_info.qmd
    - practical_delivery.qmd
    - data_cleaning.qmd
    - styling_tables.qmd
    - charts.qmd
    - choropleth_maps.qmd
  appendices:
    - glossary.qmd
    - resources.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    code-line-numbers: true
    code-copy: hover
    highlight-style: a11y

editor: source